# Generated by Django 4.1.3 on 2022-11-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=30)),
                ('asset_type', models.CharField(max_length=30)),
                ('asset_price', models.IntegerField()),
                ('asset_purchase_date', models.DateField()),
                ('asset_warranty', models.IntegerField()),
                ('asset_status', models.CharField(max_length=30)),
                ('asset_location', models.CharField(max_length=30)),
                ('asset_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AssetAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_assign_date', models.DateField()),
                ('asset_return_date', models.DateField()),
                ('asset_assign_status', models.CharField(max_length=30)),
                ('asset_log', models.CharField(max_length=30)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.assets')),
            ],
        ),
    ]
